version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - revive
    - misspell
  settings:
    revive:
      rules:
        - name: exported
          severity: warning
          disabled: false
  exclusions:
    presets: []
    rules: []

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
